# Generated by Django 4.2.1 on 2023-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='total_count',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
