# Generated by Django 4.2.1 on 2023-05-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0002_designation_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='', max_length=240, null=True)),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('fathername', models.CharField(max_length=240, null=True)),
                ('mothername', models.CharField(max_length=240, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=240, null=True)),
                ('address', models.CharField(max_length=240, null=True)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('district', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('alternativeno', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('username', models.CharField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('idproof', models.FileField(blank=True, null=True, upload_to='images/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('attitude', models.IntegerField(default='0')),
                ('creativity', models.IntegerField(default='0')),
                ('workperformance', models.IntegerField(default='0')),
                ('joiningdate', models.DateField(auto_now_add=True, null=True)),
                ('startdate', models.DateField(auto_now_add=True, null=True)),
                ('enddate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=240, null=True)),
                ('total_pay', models.IntegerField(default='0')),
                ('payment_balance', models.IntegerField(default='0')),
                ('account_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ifsc', models.CharField(default='', max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('bank_branch', models.CharField(default='', max_length=240, null=True)),
                ('payment_status', models.CharField(default='', max_length=200, null=True)),
                ('google_pay', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('paypal', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('applepay', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('confirm_salary', models.IntegerField(default='0')),
                ('confirm_salary_status', models.CharField(default='0', max_length=255)),
                ('payment_file_downlod', models.FileField(blank=True, null=True, upload_to='images/')),
                ('total_amount', models.IntegerField(default='0')),
                ('payment_amount_date', models.DateField(blank=True, null=True)),
                ('salary_pending', models.CharField(default='', max_length=100)),
                ('salary_status', models.CharField(default='', max_length=10)),
                ('reg_status', models.CharField(default='0', max_length=10)),
                ('aadhar_no', models.CharField(default='0', max_length=20)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.designation')),
            ],
        ),
    ]
