# Generated by Django 4.2.1 on 2023-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
