# Generated by Django 4.2.1 on 2023-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_staff_registration_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='attendance_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
