# Generated by Django 4.2.1 on 2023-05-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0003_staff_registration_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('attendance_status', models.CharField(max_length=200, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('today_work', models.CharField(max_length=200, null=True)),
                ('work_report', models.CharField(max_length=200, null=True)),
                ('work_progress', models.CharField(max_length=200, null=True)),
                ('half_day_status', models.CharField(max_length=200, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.staff_registration')),
            ],
        ),
    ]
