# Generated by Django 4.2.1 on 2023-06-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0005_staff_login_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='he_is_a',
            field=models.CharField(default='DEVELOPER', max_length=10),
        ),
    ]
