# Generated by Django 4.2.1 on 2023-06-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0006_staff_registration_he_is_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, null=True)),
                ('task_links', models.CharField(max_length=200, null=True)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(default='0', max_length=200)),
                ('task_progress', models.CharField(max_length=200, null=True)),
                ('task_progress_reports', models.CharField(max_length=200, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.staff_registration')),
            ],
        ),
    ]
