# Generated by Django 4.2.1 on 2023-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0007_staff_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_tasks',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
