# Generated by Django 4.2.1 on 2023-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0008_alter_staff_tasks_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='checkin_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
