# Generated by Django 4.2.1 on 2023-06-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0009_staff_registration_checkin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='staffs_basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField()),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('tea_time_start', models.DateTimeField(blank=True, null=True)),
                ('tea_time_end', models.DateTimeField(blank=True, null=True)),
                ('lunch_time_start', models.DateTimeField(blank=True, null=True)),
                ('lunch_time_end', models.DateTimeField(blank=True, null=True)),
                ('over_time_start', models.DateTimeField(blank=True, null=True)),
                ('over_time_end', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.staff_registration')),
            ],
        ),
    ]
