# Generated by Django 4.2.1 on 2023-06-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0010_attendance_checkin_time_attendance_checkout_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today_work',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_progress',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_report',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
