# Generated by Django 4.2.1 on 2023-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0013_alter_attendance_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_tasks',
            name='task_progress_reports',
            field=models.CharField(default='No Reports', max_length=200, null=True),
        ),
    ]
