# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0014_alter_staff_tasks_task_progress_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_tasks',
            name='task_progress',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
