# Generated by Django 4.2.1 on 2023-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0016_staff_project_task_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_project_task_reports',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
