# Generated by Django 4.2.1 on 2023-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0017_staff_project_task_reports_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='iam_doing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
