# Generated by Django 4.2.1 on 2023-06-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0018_staff_registration_iam_doing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=200, null=True)),
                ('Project_links', models.CharField(max_length=200, null=True)),
                ('Project_file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('Project_status', models.CharField(default='0', max_length=200)),
                ('Project_progress', models.CharField(default='0', max_length=200, null=True)),
                ('Project_progress_reports', models.CharField(default='No Reports', max_length=200, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.staff_registration')),
            ],
        ),
    ]
