# Generated by Django 4.2.1 on 2023-06-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0021_alter_staff_tasks_task_cancel_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Day_Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_countodunt', models.CharField(default='00:00:00', max_length=20)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('total_break_time', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('attendance_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.attendance')),
            ],
        ),
    ]
