# Generated by Django 4.2.1 on 2023-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0023_attendance_day_break_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_day_break',
            name='total_break_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
